In [81]:
import pandas
import numpy as np
import urllib
import googlemaps
import json
import time, datetime
from sklearn.feature_extraction.text import TfidfVectorizer
import nltk
from nltk.stem.porter import *
import string
from string import punctuation
from bs4 import BeautifulSoup
import math
from sklearn.ensemble import RandomForestClassifier
import pickle
import os
import random
from sklearn.metrics  import log_loss
from sklearn.multiclass import OneVsRestClassifier

In [2]:
# panda_data = pandas.read_json('../train.json')
# panda_test_data = pandas.read_json('test.json')

In [3]:
# with open('records.json', 'w') as outfile:
#     json.dump(json.loads(panda_data.to_json(orient='records')), outfile)
    
# with open('records_test.json', 'w') as outfile:
#     json.dump(json.loads(panda_test_data.to_json(orient='records')), outfile)

In [4]:
def expressStatus(status):
    print status
    os.system('say "' + str(status) + '"')

In [15]:
# def parseData(fname):
#     for l in urllib.urlopen(fname):
#         yield eval(l)
        
# data = np.transpose(list(parseData('records.json')))
# test_data = np.transpose(list(parseData('records_test.json')))

In [6]:
for i, k in enumerate(data[0][0]):
    print i+1, '.', k, ':', data[0][0][k]


1 . display_address : Metropolitan Avenue
2 . description : A Brand New 3 Bedroom 1.5 bath ApartmentEnjoy These Following Apartment Features As You Rent Here? Modern Designed Bathroom w/ a Deep Spa Soaking Tub? Room to Room AC/Heat? Real Oak Hardwood Floors? Rain Forest Shower Head? SS steel Appliances w/ Chef Gas Cook Oven & LG Fridge? washer /dryer in the apt? Cable Internet Ready? Granite Counter Top Kitchen w/ lot of cabinet storage spaceIt's Just A Few blocks To L Train<br /><br />Don't miss out!<br /><br />We have several great apartments in the immediate area.<br /><br />For additional information 687-878-2229<p><a  website_redacted 
3 . price : 3000
4 . bedrooms : 3
5 . photos : ['https://photos.renthop.com/2/7211212_1ed4542ec81621d70d1061aa833e669c.jpg', 'https://photos.renthop.com/2/7211212_7dfc41dced69245065df83d08eed4a00.jpg', 'https://photos.renthop.com/2/7211212_c17853c4b869af6f53af08b0f5820b4c.jpg', 'https://photos.renthop.com/2/7211212_787ad8ea0c089792e7453e2121f8ac89.j

In [5]:
# def stem_tokens(tokens, stemmer):
#     stemmed = []
#     for item in tokens:
#         stemmed.append(stemmer.stem(item))
#     return stemmed

# def tokenize(text, stemmer=PorterStemmer()):
#     tokens = nltk.word_tokenize(text)
#     stems = stem_tokens(tokens, stemmer)
#     return stems

# tfidf = TfidfVectorizer(tokenizer=tokenize, stop_words='english')

# def trainTfIdfModel(strings):
#     content = np.array([])
#     tfIdfScores = np.array([])
#     print 'Preprocessing Data'
#     for s in strings:
#         t = " ".join(item.strip() for item in BeautifulSoup(s).find_all(text=True))
#         t = str(''.join([i if ord(i) < 128 else ' ' for i in t]))
#         replace_punctuation = string.maketrans(punctuation, ' '*len(punctuation))
#         transformed_string = t.lower().translate(replace_punctuation)
#         content = np.append(content, transformed_string)
     
#     print 'Started Training'
#     tfs = tfidf.fit_transform(content)

# trainTfIdfModel([d[0]['description'] for d in data])

# def getTransformedtfIdfScore(review):
#     t = " ".join(item.strip() for item in BeautifulSoup(review).find_all(text=True))
#     t = str(''.join([i if ord(i) < 128 else ' ' for i in t]))
#     replace_punctuation = string.maketrans(punctuation, ' '*len(punctuation))
#     transformed_string = t.lower().translate(replace_punctuation)
#     response = tfidf.transform([transformed_string])
    
# #     feature_names = tfidf.get_feature_names()
# #     for col in response.nonzero()[1]:
# #         print feature_names[col], ' - ', response[0, col]
    
# #     print response.nonzero()[1]
#     if float(response.nonzero()[1].shape[0]) == 0:
#         return 0
#     return float(np.sum([response[0, col] for col in response.nonzero()[1]])) / float(response.nonzero()[1].shape[0])

In [16]:
# def getARI(string):
#     string = " ".join(item.strip() for item in BeautifulSoup(string).find_all(text=True))
#     string = str(''.join([i if ord(i) < 128 else ' ' for i in string]))
#     s_count = float(len(nltk.sent_tokenize(string)))
#     w_count = float(len(nltk.wordpunct_tokenize(string)))
#     c_count = float(len(string))
    
#     if s_count == 0:
#         return 12
    
#     return math.ceil((4.71*(c_count/w_count)) + (0.5*(w_count/s_count)) - 21.43)



# def GetFeatures(data):
#     structured_data = []
#     index = 1
#     for d in data:
#         feat = []
#         if index % 10000 == 1:
#             print 'Starting', index
            
#         feat.append(time.mktime(datetime.datetime.strptime(d[0]['created'], "%Y-%m-%d %H:%M:%S").timetuple()))
#         feat.append(getTransformedtfIdfScore(d[0]['description']))
#         feat.append(getARI(d[0]['description']))
#         structured_data.append(feat)
#         if index % 10000 == 1:
#             print 'Done', index
#         index += 1
    
#     return structured_data

In [17]:
# new_data = GetFeatures(data)
# new_test_data = GetFeatures(test_data)

Starting 1
Done 1
Starting 10001
Done 10001
Starting 20001
Done 20001
Starting 30001
Done 30001
Starting 40001
Done 40001
Starting 1
Done 1
Starting 10001
Done 10001
Starting 20001
Done 20001
Starting 30001
Done 30001
Starting 40001
Done 40001
Starting 50001
Done 50001
Starting 60001
Done 60001
Starting 70001
Done 70001


In [19]:
print new_data[0]
print np.array(new_data).shape

print new_test_data[0]
print np.array(new_test_data).shape

 [1466780064.0, 0.10791517320475999, 6.0]
(49352, 3)
[1465648181.0, 0.12883028455155554, 29.0]
(74659, 3)


In [20]:
np.save('ut_tfidf_ari_train', new_data)
np.save('ut_tfidf_ari_test', new_test_data)

In [102]:
# all_features = np.load('featureX.npy')
# feature_names = []

# feature_names.append('bathrooms'),#0
# feature_names.append('bedrooms'),#1
# feature_names.append('density'),#2
# feature_names.append('interest_manager_low'),#3
# feature_names.append('interest_manager_medium'),#4
# feature_names.append('interest_manager_high'),#5
# feature_names.append('interest_manager_count'),#6
# feature_names.append('interest_building_low'),#7
# feature_names.append('interest_building_medium'),#8
# feature_names.append('interest_building_high'),#9
# feature_names.append('interest_building_count'),#10
# feature_names.append('number of features'),#11
# feature_names.append('latitude'),#12
# feature_names.append('longitude'),#13
# feature_names.append('distance from city center'),#14
# feature_names.append('number of photos'),#15
# feature_names.append('population'),#16
# feature_names.append('price'),#17
# feature_names.append('wage'),#18
# feature_names.append('unix timestamp'),#19
# feature_names.append('tfidf of description'),#20
# feature_names.append('ari of desciption'),#21,
# feature_names.append('interest level')#22
                                                 
# np.save('feature_names', feature_names)
all_features = np.load('feature_names.npy')
train_feature_index = dict([(v,i) for i,v in enumerate(all_features)])
for feature in train_feature_index:
    print feature, train_feature_index[feature]

bathrooms 0
interest_building_high 9
interest_manager_count 6
distance from city center 14
interest_building_low 7
wage 18
ari of desciption 21
density 2
interest level 22
number of features 11
latitude 12
interest_building_medium 8
unix timestamp 19
price 17
bedrooms 1
interest_building_count 10
interest_manager_high 5
population 16
tfidf of description 20
interest_manager_medium 4
longitude 13
number of photos 15
interest_manager_low 3


In [103]:
print all_features.shape, all_features[0]

(23,) bathrooms


In [104]:
# feature_names_test = []

# feature_names_test.append('bathrooms'),#0
# feature_names_test.append('bedrooms'),#1
# feature_names_test.append('density'),#2
# feature_names_test.append('interest_manager_low'),#3
# feature_names_test.append('interest_manager_medium'),#4
# feature_names_test.append('interest_manager_high'),#5
# feature_names_test.append('interest_manager_count'),#6
# feature_names_test.append('interest_building_low'),#7
# feature_names_test.append('interest_building_medium'),#8
# feature_names_test.append('interest_building_high'),#9
# feature_names_test.append('interest_building_count'),#10
# feature_names_test.append('number of features'),#11
# feature_names_test.append('latitude'),#12
# feature_names_test.append('longitude'),#13
# feature_names_test.append('distance from city center'),#14
# feature_names_test.append('number of photos'),#15
# feature_names_test.append('population'),#16
# feature_names_test.append('price'),#17
# feature_names_test.append('wage')#18
# feature_names_test.append('unix timestamp'),#19
# feature_names_test.append('tfidf of description'),#20
# feature_names_test.append('ari of desciption')#21,

# np.save('feature_names_test', feature_names_test)

all_features_test = np.load('feature_names_test.npy')
test_feature_index = dict([(v,i) for i,v in enumerate(all_features_test)])
for feature in test_feature_index:
    print feature, test_feature_index[feature]

bathrooms 0
interest_building_high 9
interest_manager_count 6
distance from city center 14
interest_building_low 7
wage 18
ari of desciption 21
density 2
number of features 11
latitude 12
interest_building_medium 8
unix timestamp 19
price 17
bedrooms 1
interest_building_count 10
interest_manager_high 5
population 16
tfidf of description 20
interest_manager_medium 4
longitude 13
number of photos 15
interest_manager_low 3


In [108]:
def extract_features(datum, index_dictionary):
    feat = []
    feat.append(datum[index_dictionary['bathrooms']])
    feat.append(datum[index_dictionary['bedrooms']])
    feat.append(datum[index_dictionary['interest_manager_count']])
    feat.append(datum[index_dictionary['interest_building_count']])
    
    feat.append(datum[index_dictionary['distance from city center']])
    feat.append(datum[index_dictionary['wage']])
    feat.append(datum[index_dictionary['price']])
    feat.append(datum[index_dictionary['ari of desciption']])
    feat.append(datum[index_dictionary['density']])
    feat.append(datum[index_dictionary['number of features']])
    feat.append(datum[index_dictionary['unix timestamp']])
    feat.append(datum[index_dictionary['population']])
    feat.append(datum[index_dictionary['tfidf of description']])
    feat.append(datum[index_dictionary['number of photos']])
    
#     feat.append(2*datum[index_dictionary['interest_building_high']] +
#                 1*datum[index_dictionary['interest_building_medium']] +
#                 0*datum[index_dictionary['interest_building_low']])
    
#     feat.append(2*datum[index_dictionary['interest_manager_high']] +
#                 1*datum[index_dictionary['interest_manager_medium']] +
#                 0*datum[index_dictionary['interest_manager_low']])
    return feat

In [109]:
def truncate_data(data, index_dictionary):
    data = np.array([d for d in data if d[index_dictionary['distance from city center']] < 0.2])
    return data

In [110]:
data_features = np.load('featureX.npy')
print data_features.shape, all_features.shape
random.shuffle(data_features)
validation_count = int(data_features.shape[0] * 0.2)
train_data = truncate_data(data_features[:-validation_count], train_feature_index)
train_X = np.array([extract_features(d, train_feature_index) for d in train_data])
train_y = np.array([d[train_feature_index['interest level']] for d in train_data])


validation_X = np.array([extract_features(d, train_feature_index) for d in data_features[-validation_count:]])
validation_y = np.array([d[train_feature_index['interest level']] for d in data_features[-validation_count:]])

test_features = np.load('X_test.npy')
print test_features.shape, all_features_test.shape
test_X = np.array([extract_features(d, test_feature_index) for d in test_features])
print train_X.shape, test_X.shape, train_y.shape, validation_X.shape, validation_y.shape

(49352, 23) (23,)
(74659, 23) (22,)
(39347, 14) (74659, 14) (39347,) (9870, 14) (9870,)


In [111]:
n_estimators = 100
max_features = None
max_depth = 17
oob_score = True
verbose = 2
min_samples_leaf = 17
n_jobs = -1

expressStatus("Training random forest model with " + str(n_estimators) + " estimators and max depth "+ str(max_depth) + " and " + str(train_X[0].shape[0]) + " features")
rf = RandomForestClassifier(max_features=max_features, n_estimators=n_estimators, criterion='entropy', max_depth = max_depth, verbose = verbose, n_jobs=n_jobs, min_samples_leaf=min_samples_leaf, oob_score=oob_score)#, max_features=max_features
rf.fit(train_X, train_y)

train_predictions = rf.predict_proba(train_X)
validation_predictions = rf.predict_proba(validation_X)


print train_predictions.shape, train_predictions[0]
expressStatus("Done training model!")

Training random forest model with 100 estimators and max depth 17 and 14 features
building tree 1 of 100building tree 2 of 100
  building tree 4 of 100
building tree 3 of 100

building tree 5 of 100
building tree 6 of 100
building tree 7 of 100
building tree 8 of 100
building tree 9 of 100building tree 10 of 100
 
building tree 11 of 100 
building tree 12 of 100
building tree 13 of 100
building tree 14 of 100building tree 15 of 100 

building tree 16 of 100
building tree 17 of 100
building tree 18 of 100
building tree 19 of 100
building tree 20 of 100
building tree 21 of 100
building tree 22 of 100
building tree 23 of 100
building tree 24 of 100
building tree 25 of 100
building tree 26 of 100
building tree 27 of 100
building tree 28 of 100
building tree 29 of 100
building tree 30 of 100
building tree 31 of 100
building tree 32 of 100
building tree 33 of 100
building tree 34 of 100
building tree 35 of 100
building tree 36 of 100


[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:    3.3s


building tree 37 of 100
building tree 38 of 100
building tree 39 of 100
building tree 40 of 100
building tree 41 of 100
building tree 42 of 100
building tree 43 of 100
building tree 44 of 100
building tree 45 of 100
building tree 46 of 100
building tree 47 of 100
building tree 48 of 100
building tree 49 of 100
building tree 50 of 100
building tree 51 of 100
building tree 52 of 100
building tree 53 of 100
building tree 54 of 100
building tree 55 of 100
building tree 56 of 100
building tree 57 of 100
building tree 58 of 100
building tree 59 of 100
building tree 60 of 100
building tree 61 of 100
building tree 62 of 100
building tree 63 of 100
building tree 64 of 100
building tree 65 of 100
building tree 66 of 100
building tree 67 of 100
building tree 68 of 100
building tree 69 of 100
building tree 70 of 100
building tree 71 of 100
building tree 72 of 100
building tree 73 of 100
building tree 74 of 100
building tree 75 of 100
building tree 76 of 100
building tree 77 of 100
building tree 78

[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:   11.0s finished
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    0.1s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.3s finished
[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.1s finished


(39347, 3) [ 0.29321145  0.66553676  0.04125179]
Done training model!


In [113]:
print 'Cross entropy loss on train data:', log_loss(train_y, train_predictions)
print 'Cross entropy loss on validation data:', log_loss(validation_y, validation_predictions)

Cross entropy loss on train data: 0.3761130245
Cross entropy loss on validation data: 0.543418635311


In [114]:
test_predictions = np.array(rf.predict_proba(test_X))

[Parallel(n_jobs=4)]: Done  33 tasks      | elapsed:    0.2s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.5s finished


In [116]:
output = open('result.txt', 'w')
output.write("listing_id,high,medium,low\n")
for i in range(len(test_X)):
    output.write(str(int(test_features[i][22])) + ',' + str(test_predictions[i][2]) + ',' + str(test_predictions[i][1]) + ',' + str(test_predictions[i][0]) + '\n')
output.close()

print test_predictions[:10]

[[ 0.53971962  0.36017488  0.1001055 ]
 [ 0.88130534  0.10663136  0.0120633 ]
 [ 0.90604354  0.08814643  0.00581002]
 [ 0.61318152  0.28249989  0.1043186 ]
 [ 0.64850524  0.32658485  0.02490991]
 [ 0.97673788  0.02326212  0.        ]
 [ 0.45131092  0.48728216  0.06140692]
 [ 0.67468341  0.22868983  0.09662675]
 [ 0.52655208  0.30465021  0.16879771]
 [ 0.79240135  0.17816945  0.0294292 ]]


In [65]:
for name in test_feature_index:
    print name, test_features[0][test_feature_index[name]]

bathrooms 1.0
interest_building_high 0.0
interest_manager_count 24.0
distance from city center 0.0690372906913
interest_building_low 0.0
wage 17123.723916
ari of desciption 29.0
density 92511.3636364
number of features 6.0
latitude 40.7185
interest_building_medium 1.0
unix timestamp 1465648181.0
price 2950.0
bedrooms 1.0
interest_building_count 3.0
interest_manager_high 0.208333333333
population 81410.0
tfidf of description 0.128830284552
interest_manager_medium 0.333333333333
longitude -73.9865
number of photos 8.0
interest_manager_low 0.458333333333
